### ISSUE TITLE
Make super image use local path as opposed to a URL?

### ISSUE THREAD

**Issue by LinuxBeaver** [eugenesiow/super-image#1]
Hey, I am a fan of open source machine learning software that can replace Adobe. However, I need help getting Super-Image to accept local image paths as of now it only accepts URLS. What modifications do I need to make here?

from super_image import EdsrModel, ImageLoader
from PIL import Image
import requests

url = 'file:///home/contrast/Desktop/dude.png'
image = Image.open(requests.get(url, stream=True).raw)

model = EdsrModel.from_pretrained('eugenesiow/edsr-base', scale=2)
inputs = ImageLoader.load_image(image)
preds = model(inputs)

ImageLoader.save_image(preds, './scaled_2x.png')
ImageLoader.save_compare(inputs, preds, './scaled_2x_compare.png')

**Comment by eugenesiow** [comment]
To use a local image path, try replacing the `Image.open()` bit of code with the following line, where you specify your local image 
 path directly:

```python
image = Image.open('/home/contrast/Desktop/dude.png')
```

**Comment by LinuxBeaver** [comment]
Thanks. I already figured it out hours after I made that post.

`from super_image import EdsrModel, ImageLoader
from PIL import Image, ImageFilter
import requests
import os

image = Image.open(open("/home/contrast/Desktop/CopyQ.Ti2305.png", 'rb'))

model = EdsrModel.from_pretrained('eugenesiow/edsr-base', scale=2)
inputs = ImageLoader.load_image(image)
preds = model(inputs)

ImageLoader.save_image(preds, './scaled_2x.png')
ImageLoader.save_compare(inputs, preds, './scaled_2x_compare.png')
`
